spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=chat_app
spring.mongodb.username=admin
spring.mongodb.password=pass
spring.mongodb.authentication-database=admin

server.port=8088